const APP_PERMISSIONS = {
  groups: [
    {
      id: "business",
      name: "Kinh doanh",
      description: "Thống kê, Page, tin nhắn, chatbot và đơn hàng",
      screenIds: [
        "business_stats",
        "pages",
        "meta_pages",
        "pagesmessage",
        "customer_care",
        "donhang",
        "so_quy",
        "dia_chi",
      ],
    },
    {
      id: "attendance",
      name: "Chấm công",
      description:
        "Chấm công, ca làm, vị trí, tính lương và thông báo thiết bị",
      screenIds: [
        "attendance_self",
        "attendance",
        "attendance_shifts",
        "attendance_locations",
        "payroll",
        "notifications",
      ],
    },
    {
      id: "people",
      name: "Nhân sự",
      description:
        "Hồ sơ nhân sự, kho thiết bị, người dùng và vai trò phân quyền",
      screenIds: ["employee_profiles", "employee_assets", "users", "roles"],
    },
    {
      id: "finance",
      name: "Tính toán",
      description: "Công cụ tính hoa hồng",
      screenIds: ["commission_online", "commission_abc"],
    },
    {
      id: "system",
      name: "Hệ thống & AI",
      description: "Quản trị hệ thống, AI, agent, chat webhook và log",
      screenIds: [
        "admin_dashboard",
        "admin_products_tool",
        "admin_vectorstore_tool",
        "admin_agent",
        "admin_agent_intent",
        "admin_agent_promo",
        "admin_agent_response_templates",
        "admin_logs",
      ],
    },
    {
      id: "experimental",
      name: "Phiên bản thử nghiệm",
      description: "FAQ theo Page và khuyến mãi",
      screenIds: [
        "admin_event_promo",
        "admin_faq",
      ],
    },
    {
      id: "agriculture",
      name: "Nông nghiệp",
      description: "Quản lý nghiệp vụ nông nghiệp",
      screenIds: ["dua_sap"],
    },
  ],
  screens: [
    { id: "pages", name: "Quản Lý Page" },
    { id: "meta_pages", name: "Kết nối Meta Page" },
    { id: "pagesmessage", name: "Tin Nhắn Page" },
    { id: "customer_care", name: "Chăm sóc khách hàng" },
    { id: "donhang", name: "Đơn Hàng" },
    { id: "business_stats", name: "Thống kê kinh doanh" },
    { id: "dia_chi", name: "Địa chỉ" },
    { id: "employee_profiles", name: "Hồ Sơ Nhân Sự" },
    { id: "employee_assets", name: "Kho Tài Sản & Vật Tư" },
    { id: "users", name: "Người Dùng" },
    { id: "roles", name: "Phân quyền" },
    { id: "commission_online", name: "Tính Hoa Hồng Online" },
    { id: "commission_abc", name: "Tính Hoa Hồng ABC" },
    { id: "admin_dashboard", name: "Quản Trị Hệ Thống" },
    { id: "admin_products_tool", name: "Quản Trị Sản Phẩm" },
    { id: "admin_event_promo", name: "Chương Trình Khuyến Mãi Chung" },
    { id: "admin_vectorstore_tool", name: "Quản Trị Vector DB" },
    { id: "admin_agent", name: "Quản Trị Agent" },
    { id: "admin_agent_intent", name: "Quản Lý Intent" },
    { id: "admin_agent_promo", name: "Quản Lý Khuyến Mãi" },
    {
      id: "admin_agent_response_templates",
      name: "Mẫu câu trả lời theo intent",
    },
    { id: "admin_faq", name: "FAQ Theo Page" },
    { id: "admin_logs", name: "Log Hệ Thống" },
    { id: "notifications", name: "Thông Báo Thiết Bị" },
    { id: "attendance_self", name: "Chấm công của tôi" },
    { id: "attendance", name: "Quản lý chấm công" },
    { id: "attendance_shifts", name: "Ca làm" },
    { id: "attendance_locations", name: "Vị trí chấm công" },
    { id: "payroll", name: "Chấm công tính lương" },
    { id: "dua_sap", name: "Quản Lý Dừa Sáp" },
    { id: "so_quy", name: "Tính Sổ Quỹ" },
  ],
  actions: [
    { id: "view", name: "Xem", color: "blue" },
    { id: "create", name: "Thêm mới", color: "emerald" },
    { id: "edit", name: "Chỉnh sửa", color: "amber" },
    { id: "delete", name: "Xóa", color: "red" },
    { id: "export", name: "Xuất file", color: "slate" },
  ],
};

export default APP_PERMISSIONS;
