const APP_PERMISSIONS = {
  groups: [
    {
      id: "business",
      name: "Kinh doanh",
      description: "Thống kê, Page, tin nhắn, chatbot và đơn hàng",
      screenIds: ["business_stats", "pages", "pagesmessage", "chatweb", "donhang", "donhangWeb"],
    },
    {
      id: "attendance",
      name: "Chấm công",
      description: "Chấm công, ca làm, vị trí, tính lương và thông báo thiết bị",
      screenIds: ["attendance_self", "attendance", "attendance_shifts", "attendance_locations", "payroll", "notifications"],
    },
    {
      id: "people",
      name: "Nhân sự",
      description: "Người dùng và vai trò phân quyền",
      screenIds: ["users", "roles"],
    },
    {
      id: "finance",
      name: "Tính toán",
      description: "Công cụ tính hoa hồng",
      screenIds: ["commission_online", "commission_abc"],
    },
    {
      id: "system",
      name: "Hệ thống & AI",
      description: "Quản trị hệ thống, AI, Chat V3, agent, cấu hình và log",
      screenIds: [
        "admin_dashboard",
        "admin_products_tool",
        "admin_vectorstore_tool",
        "admin_chat_v3_file_search",
        "admin_chat_v3_contexts",
        "admin_chat_v3_rules",
        "admin_chat_v3_try",
        "admin_agent",
        "admin_agent_intent",
        "admin_agent_promo",
        "admin_agent_response_templates",
        "admin_chatbot_config",
        "admin_chat_v3_faq",
        "admin_logs",
      ],
    },
    {
      id: "experimental",
      name: "Phiên bản thử nghiệm",
      description: "Các màn thử nghiệm, Chat V4, FAQ theo Page và khuyến mãi",
      screenIds: [
        "admin_event_promo",
        "admin_chat_v4_rules",
        "admin_faq",
        "admin_chat_v4_function_calls",
        "admin_chat_v4_contexts",
        "admin_chat_v4_settings",
        "admin_chat_v4_simulator",
      ],
    },
    {
      id: "agriculture",
      name: "Nông nghiệp",
      description: "Quản lý nghiệp vụ nông nghiệp",
      screenIds: ["dua_sap"],
    },
  ],
  screens: [
    { id: "pages", name: "Quản Lý Page" },
    { id: "pagesmessage", name: "Tin Nhắn Page" },
    { id: "chatweb", name: "Chatbot Web" },
    { id: "donhang", name: "Đơn Hàng" },
    { id: "donhangWeb", name: "Đơn Hàng Web" },
    { id: "business_stats", name: "Thống kê kinh doanh" },
    { id: "users", name: "Người Dùng" },
    { id: "roles", name: "Phân quyền" },
    { id: "commission_online", name: "Tính Hoa Hồng Online" },
    { id: "commission_abc", name: "Tính Hoa Hồng ABC" },
    { id: "admin_dashboard", name: "Quản Trị Hệ Thống" },
    { id: "admin_products_tool", name: "Quản Trị Sản Phẩm" },
    { id: "admin_event_promo", name: "Chương Trình Khuyến Mãi Chung" },
    { id: "admin_vectorstore_tool", name: "Quản Trị Vector DB" },
    { id: "admin_chat_v3_file_search", name: "File Search Chat V3" },
    { id: "admin_chat_v3_contexts", name: "Ngữ cảnh Chat V3" },
    { id: "admin_chat_v3_try", name: "Chat thử v3" },
    { id: "admin_agent", name: "Quản Trị Agent" },
    { id: "admin_agent_intent", name: "Quản Lý Intent" },
    { id: "admin_agent_promo", name: "Quản Lý Khuyến Mãi" },
    { id: "admin_agent_response_templates", name: "Mẫu câu trả lời theo intent" },
    { id: "admin_chatbot_config", name: "Cấu Hình ChatBot" },
    { id: "admin_chat_v3_faq", name: "Bộ câu hỏi dùng chung" },
    { id: "admin_faq", name: "FAQ Theo Page" },
    { id: "admin_chat_v4_rules", name: "Quy tắc Chat V4" },
    { id: "admin_chat_v3_rules", name: "Luật vận hành Chat V3" },
    { id: "admin_chat_v4_function_calls", name: "Function Call Chat V4" },
    { id: "admin_chat_v4_contexts", name: "Ngữ cảnh Chat V4" },
    { id: "admin_chat_v4_settings", name: "Cài đặt Chat V4" },
    { id: "admin_chat_v4_simulator", name: "Giả lập Event Chat V4" },
    { id: "admin_logs", name: "Log Hệ Thống" },
    { id: "notifications", name: "Thông Báo Thiết Bị" },
    { id: "attendance_self", name: "Chấm công của tôi" },
    { id: "attendance", name: "Quản lý chấm công" },
    { id: "attendance_shifts", name: "Ca làm" },
    { id: "attendance_locations", name: "Vị trí chấm công" },
    { id: "payroll", name: "Chấm công tính lương" },
    { id: "dua_sap", name: "Quản Lý Dừa Sáp" },
  ],
  actions: [
    { id: "view", name: "Xem", color: "blue" },
    { id: "create", name: "Thêm mới", color: "emerald" },
    { id: "edit", name: "Chỉnh sửa", color: "amber" },
    { id: "delete", name: "Xóa", color: "red" },
    { id: "export", name: "Xuất file", color: "slate" },
  ],
};

export default APP_PERMISSIONS;
